from django.conf.urls import include, url
from django.urls import path
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('index/', views.IndexView.as_view()),
    path('add-user/', views.AddUserView.as_view(), name='add-user'),
    path('users/', views.UsersView.as_view(), name='users'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('recover/', views.RecoverView.as_view(), name='recover'),
    path('set-pw/', views.SetPWView.as_view(), name='set-pw'),
    path('revenue/', views.RevenueView.as_view(), name='revenue'),
    path('revenue-details/', views.RevenueDetailsView.as_view(), name='revenue-details'),
    
    path('00_styleguide/', TemplateView.as_view(template_name='cadmin/__src__/00_styleguide.html')),
    path('02_popups/', TemplateView.as_view(template_name='cadmin/__src__/02_popups.html')),
    # path('login/', TemplateView.as_view(template_name='cadmin/__src__/login.html')),
    # path('recover/', TemplateView.as_view(template_name='cadmin/__src__/recover.html')),
    # path('set-pw/', TemplateView.as_view(template_name='cadmin/__src__/set-pw.html')),
    # path('revenue/', TemplateView.as_view(template_name='cadmin/__src__/revenue.html')),
    # path('revenue-details/', TemplateView.as_view(template_name='cadmin/__src__/revenue-details.html')),
    path('id-verify-app/', TemplateView.as_view(template_name='cadmin/__src__/id-verify-app.html')),
    path('id-verify-app-details/', TemplateView.as_view(template_name='cadmin/__src__/id-verify-app-details.html')),
    path('customers/', TemplateView.as_view(template_name='cadmin/__src__/customers.html')),
    path('customer-details/', TemplateView.as_view(template_name='cadmin/__src__/customer-details.html')),
    path('transactions/', TemplateView.as_view(template_name='cadmin/__src__/transactions.html')),
    path('transaction-details/', TemplateView.as_view(template_name='cadmin/__src__/transaction-details.html')),
    path('escrows/', TemplateView.as_view(template_name='cadmin/__src__/escrows.html')),
    path('escrow-details/', TemplateView.as_view(template_name='cadmin/__src__/escrow-details.html')),
    path('offers/', TemplateView.as_view(template_name='cadmin/__src__/offers.html')),
    path('offer-details/', TemplateView.as_view(template_name='cadmin/__src__/offer-details.html')),
    path('trades/', TemplateView.as_view(template_name='cadmin/__src__/trades.html')),
    path('trade-details/', TemplateView.as_view(template_name='cadmin/__src__/trade-details.html')),
    path('contact-form/', TemplateView.as_view(template_name='cadmin/__src__/contact-form.html')),
    path('contact-form-details/', TemplateView.as_view(template_name='cadmin/__src__/contact-form-details.html')),
    path('add-new-post/', TemplateView.as_view(template_name='cadmin/__src__/add-new-post.html')),
    path('add-new-page/', TemplateView.as_view(template_name='cadmin/__src__/add-new-page.html')),
    # path('users/', TemplateView.as_view(template_name='cadmin/__src__/users.html')),
    # path('add-user/', TemplateView.as_view(template_name='cadmin/__src__/add-user.html')),
    path('add-new-affiliate/', TemplateView.as_view(template_name='cadmin/__src__/add-new-affiliate.html')),
    path('add-redirection-link/', TemplateView.as_view(template_name='cadmin/__src__/add-redirection-link.html')),
    path('add-pers-link/', TemplateView.as_view(template_name='cadmin/__src__/add-pers-link.html')),
    path('add-landing-page/', TemplateView.as_view(template_name='cadmin/__src__/add-landing-page.html')),
    path('ticket-details-dispute/', TemplateView.as_view(template_name='cadmin/__src__/ticket-details-dispute.html')),
    path('ticket-details-no-dispute/', TemplateView.as_view(template_name='cadmin/__src__/ticket-details-no-dispute.html')),
    path('seo/', TemplateView.as_view(template_name='cadmin/__src__/seo.html')),
    path('media-library/', TemplateView.as_view(template_name='cadmin/__src__/media-library.html')),
    path('post-issue/', TemplateView.as_view(template_name='cadmin/__src__/post-issue.html')),
    path('affiliates/', TemplateView.as_view(template_name='cadmin/__src__/affiliates.html')),
    path('campaigns/', TemplateView.as_view(template_name='cadmin/__src__/campaigns.html')),
    path('reports/', TemplateView.as_view(template_name='cadmin/__src__/reports.html')),
    path('support-center/', TemplateView.as_view(template_name='cadmin/__src__/support-center.html')),
    path('tags/', TemplateView.as_view(template_name='cadmin/__src__/tags.html')),
    path('documentations/', TemplateView.as_view(template_name='cadmin/__src__/documentations.html')),
    path('last-login/', TemplateView.as_view(template_name='cadmin/__src__/last-login.html')),
    path('additional-pages/', TemplateView.as_view(template_name='cadmin/__src__/additional-pages.html')),
    path('blog/', TemplateView.as_view(template_name='cadmin/__src__/blog.html')),
    path('security-status/', TemplateView.as_view(template_name='cadmin/__src__/security-status.html')),
    path('options/', TemplateView.as_view(template_name='cadmin/__src__/options.html')),
    path('campaign-updated/', TemplateView.as_view(template_name='cadmin/__src__/campaign-updated.html')),
    path('upload/', TemplateView.as_view(template_name='cadmin/__src__/upload.html')),
    path('rev-stats/', TemplateView.as_view(template_name='cadmin/__src__/rev-stats.html')),
    path('community-posts/', TemplateView.as_view(template_name='cadmin/__src__/community-posts.html')),
    path('community-post-details/', TemplateView.as_view(template_name='cadmin/__src__/community-post-details.html')),
    path('community-post-rules/', TemplateView.as_view(template_name='cadmin/__src__/community-post-rules.html')),
    path('flagged-posts/', TemplateView.as_view(template_name='cadmin/__src__/flagged-posts.html')),
    path('flagged-content/', TemplateView.as_view(template_name='cadmin/__src__/flagged-content.html'))
]
