# Generated by Django 2.2.8 on 2019-12-19 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('contents', tinymce.models.HTMLField()),
                ('abstract', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('show_image', models.BooleanField(default=True)),
                ('show_creator', models.BooleanField(default=True)),
                ('show_comments', models.BooleanField(default=True)),
                ('creation_date', models.DateField(default='2019-12-19')),
                ('last_updated', models.DateField(default='2019-12-19')),
                ('pin_to_top', models.BooleanField(default=False)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
