# Generated by Django 2.2.8 on 2019-12-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('MO', 'Moderator'), ('IV', 'ID Verifier'), ('BM', 'Blog Manager'), ('SM', 'SEO Manager'), ('SA', 'Support Agent'), ('CM', 'Community Moderator'), ('AM', 'Affiliate Manager')], max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'p127_users',
            },
        ),
    ]
