# Generated by Django 2.2.8 on 2019-12-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('revenue_type', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('refund', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'p127_revenue',
            },
        ),
    ]
