"""
Django settings for cryptotrade project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from datetime import timedelta
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LOGIN_REDIRECT_URL = '/index'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-ftl$49mojhozrjk)ue7$1uq!-td)hn+qvrrp(6nod7#d**q*u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DEV_SERVER = 'localhost'

# site domains
CRYPTOTRADE_URL = 'beta.cryptptrade.com'
AFFILIATES_URL = 'affiliates.cryptptrade.com'
COMMUNITY_URL = 'community.cryptptrade.com'
SCREENRECODER_URL = 'srecoder.cryptptrade.com'

ALLOWED_HOSTS = [CRYPTOTRADE_URL, AFFILIATES_URL, COMMUNITY_URL, SCREENRECODER_URL, DEV_SERVER]
# for api server
HOSTNAME = 'http://beta.cryptptrade.com'

# Application definition

INSTALLED_APPS = [
    'cadmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.postgres',
    'django.contrib.staticfiles',
    'theme',
    'rest_framework',
    'corsheaders',
    'apis',
    'crypto',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apis.authentication.TokenAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100
}

CORS_ORIGIN_WHITELIST = [
    "http://" + COMMUNITY_URL,
    "http://" + AFFILIATES_URL,
]

ROOT_URLCONF = 'cryptptrade.urls'

TEMPLATES = [
   {
       'BACKEND': 'django.template.backends.django.DjangoTemplates',
       'DIRS': [],
       'APP_DIRS': True,
       'OPTIONS': {
           'context_processors': [
               'django.template.context_processors.debug',
               'django.template.context_processors.request',
               'django.contrib.auth.context_processors.auth',
               'django.contrib.messages.context_processors.messages',
               'django.template.context_processors.media',
               'cryptptrade.context_processors.global_settings',
               'cadmin.context_processors.cadmin_decorators',
               'theme.context_processors.theme_decorators',
           ],
       },
   },
]


WSGI_APPLICATION = 'cryptptrade.wsgi.application'



# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'cadmin.Users'

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# LANGUAGES = [
#   ('en', _('English')),
#   ('ru', _('Русский')),
#   ('io', _('Nigeria')),
#   ('zh-hans', _('简体中文')),
# ]

# # Add custom languages not provided by Django (io => ng)
# import django.conf.locale
# from django.conf import global_settings
# global_settings.LANGUAGES = [(x[0], x[1]) if x[0] != 'io' else ('io', 'Nigeria') for x in global_settings.LANGUAGES]
# django.conf.locale.LANG_INFO['io']['name'] = 'English'
# django.conf.locale.LANG_INFO['io']['name_local'] = u'Nigeria'

# LOCALE_PATHS = (
#     os.path.join(BASE_DIR, 'locale'),
# )


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/v-cryptptrade/static'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'staic')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = '/data/sites/v-cryptptrade/media'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600


DATE_INPUT_FORMATS = ('%d-%m-%Y', '%Y-%m-%d', '%a %B %m %Y')
TIME_INPUT_FORMATS = ('%I:%M %p', '%H:%M:%S', '%H:%M')

# Email validation settings
